Exercise 7.6
------------

Loading the data:

```{r}
library(ISLR)
attach(Wage)
library(boot)
```

Cross validation on polynomial fits indicate that we can do with a third degree polynomial.

```{r}
cv.error = rep(0,10)

for(i in 1:10){
fit  = glm(wage ~ poly(age, i),data=Wage)
cv.error[i] = cv.glm(Wage, fit, K=10)$delta[1]
}
plot(1:10, cv.error)
```

An anova analysis shows the same result:

```{r}
fit1 = lm(wage ~ poly(age, 1),data=Wage)
fit2 = lm(wage ~ poly(age, 2),data=Wage)
fit3 = lm(wage ~ poly(age, 3),data=Wage)
fit4 = lm(wage ~ poly(age, 4),data=Wage)
fit5 = lm(wage ~ poly(age, 5),data=Wage)

anova(fit1, fit2, fit3, fit4, fit5)
```

Plot:
```{r}
plot(wage~age)
fitpoints = data.frame(age = seq(range(age)[1], range(age)[2]))
lines(fitpoints$age, predict(fit3, newdata = fitpoints), col="red", lw=2)
```

Fitting step functions, we seem to need about 7 breakpoints:

```{r}
cv.error = rep(0,10)

for(i in 1:25){
  Wage$tmp = cut(age, i+1)
  fit  = glm(wage ~ tmp, data=Wage)
  cv.error[i] = cv.glm(Wage, fit, K=10)$delta[1]
}
plot(1:25, cv.error)
```

Plot:
```{r}
plot(wage~age)
fit7  = glm(wage ~ cut(age, 8), data=Wage)
lines(fitpoints$age, predict(fit7, newdata = fitpoints), col="red", lw=2)
```

